"""severity to string

Revision ID: cc713b59d0ea
Revises: 20250830_create_incidents
Create Date: 2025-08-31 04:57:37.295910
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cc713b59d0ea'
down_revision = '20250830_create_incidents'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_service_created'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status_created'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('suspected_cause', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('remediation_candidates', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_status_created'), 'incidents', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_incidents_service_created'), 'incidents', ['service', 'created_at'], unique=False)
    # ### end Alembic commands ###
